### ISSUE TITLE
ICS 2000 with Somfy RTS

### ISSUE THREAD

**Issue by Makkievld** [rdegraafwhizzkit/ics2000-hass#3]
Hi I got the ICS 2000 working with Somfy RTS. I can open and close my blinds with the smart home app and google assistant. Now I installed your plugin and I can see the blinds in HA. I can add the blinds as a light but I can't get them to open or close via HA. Can you maybe help me solve this problem?

**Comment by rdegraafwhizzkit** [comment]
Thanks for reaching out. Unfortunately I do not own any of that equipment so I'm not able to test it or develop for it. This plugin is targeted towards 'light' entities from KAKU. You see the blinds because they are listed by the ICS-2000 towards the plugin. But code for the so called OPEN_CLOSE devices is not implemented.
